lexer grammar BatchSharpLexer;

ARROBA: '@';
DECIMAL: DIGITS DOT DIGITS;
DIGIT: [0-9];
DIGITS: DIGIT+;
DOT: '.';
LETTER: LOWERCASE | UPPERCASE;
LETTERS: LETTER+;
LOWERCASE: [a-z];
NEWLINE: '\n';
NUMBER: DIGITS | DECIMAL;
NUMBERS: NUMBER+;
UPPERCASE: [A-Z];
WS: [ \t]+ -> skip;
